### ISSUE TITLE
Questions about the data preparation

### ISSUE THREAD

**Issue by castdice** [jialuli-luka/VLN-SIG#1]
Thank you for your excellent work! I have some questions about the data preparation. I noticed that img_db_file has a different directory structure, e.g., 'views_img/r1Q1Z4BcV1o/a72aa7b4304f4c318af76653d9950c80/5.jpg', which is different from the original directory structure in matterport3d. 

Could you please provide some details of dataset re-organization? For example, where should I find the 'views_img/r1Q1Z4BcV1o/a72aa7b4304f4c318af76653d9950c80/5.jpg' in matterport3d dataset? Thank you for your patience.

**Comment by lizixiaoboluo** [comment]
I also notice this. Have you sloved this problem？

**Comment by LifeLLearning** [comment]
@lizixiaoboluo Hello, have you resolved this issue?

**Comment by jialuli-luka** [comment]
As many of you might have trouble getting the discretized views, please send me an email with the confirmation email from Matterport3D (indicating that you have access to the dataset), and I will share a download link for the discretized views.

**Comment by LifeLLearning** [comment]
Hello, I saw your reply on VLN-SIG's GitHub. I don't know how to obtain discretized views. Attached is the email granting permission to use Matterport3D data. I'm looking forward to your sharing the download link for discretized views.


Thank you very much.




该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jialuli-luka/VLN-SIG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月5日(星期三) 上午10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jialuli-luka/VLN-SIG] Questions about the data preparation (Issue #1)





 
As many of you might have trouble getting the discretized views, please send me an email with the confirmation email from Matterport3D (indicating that you have access to the dataset), and I will share a download link for the discretized views.

**Comment by jialuli-luka** [comment]
Hi, 
Please email me the confirmation email, as I cannot share the download link publicly.
