### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'views_img/

### ISSUE THREAD

**Issue by LifeLLearning** [jialuli-luka/VLN-SIG#3]
"Hello, congratulations on the great work! When I ran the code for the pre-training part, I encountered an error 'FileNotFoundError: [Errno 2] No such file or directory: 'views_img/sT4fr6TAbpF/2f5285734159491fa089541bf820e528/4.jpg'". Could you please tell me how to obtain the data in the 'views_img' folder?

Thanks！

**Comment by jialuli-luka** [comment]
You could get these discretized images from the Matterport3D Simulator.

**Comment by 1148616553** [comment]
> You could get these discretized images from the Matterport3D Simulator.

Thank you for your response. However, I'm sorry to say that I still haven't figured out where to download this discrete images. When I installed the MatterSim simulator, following the instructions, I only downloaded the 'matterport_skybox_images' dataset, which contains only six images per route (indexed from 0 to 5), and I couldn't find the discrete images I need. I would greatly appreciate it if you could provide me with some more detailed guidance.

**Comment by LifeLLearning** [comment]
@jialuli-luka 
Sorry to bother you again. I'm sorry to say that I still haven't figured out where to download this discrete dataset. When I installed the MatterSim simulator, following the instructions, I only downloaded the 'matterport_skybox_images' dataset, which contains only six images per route (indexed from 0 to 5), and I couldn't find the discrete images I need. I would greatly appreciate it if you could provide me with some more detailed guidance.

**Comment by jialuli-luka** [comment]
You might want to refer to the feature extraction code here: https://github.com/cshizhe/VLN-HAMT/blob/main/preprocess/precompute_img_features_vit.py. This code shows how you could get the RGB of each discretized views with the simulator.
