### ISSUE TITLE
RxR fine-tuned model release

### ISSUE THREAD

**Issue by wdqin** [jialuli-luka/VLN-SIG#4]
Hi,

Is there a chance for you to release your fine-tuned model for RxR just like R2R and CVDN? Thanks!

**Comment by jialuli-luka** [comment]
Hi,
    I just upload the RxR ckpt in dropbox: https://www.dropbox.com/sh/ugpdl1q04xj0ht2/AAAANVRq7ZfAHLfuQXJ9bTo4a?dl=0

Best,
Jialu
